# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 888895ae69128edb55b8913aac94aacd46c9f7f6dd351ef77b8a816f47c12c1f76a394599ac99e9bbb5fd2dd0fd64c53f8b9519681cb536e942e10372fb3b33d

test:
  secret_key_base: 1252ec0fad80d5bf8131b27a25c9cb12d02d4c3a1a280e8fb8eb8a9a72a0abba09e53867c81e8aaed1f2fd1d7c641722fc4c2cb07e79b0b7a47e3735d9810988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
